# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mobile Data Usage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftLint'
  pod 'NVActivityIndicatorView'


  # Pods for Mobile Data Usage

end
